# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runtui < Formula
  desc "Interactive TUI for running project tasks"
  homepage "https://github.com/pedromendonka/runtui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.0/runtui_darwin_amd64.tar.gz"
      sha256 "f116585afd945ac0d79de022eb25dae473bc184872033a44a21bc59262914761"

      define_method(:install) do
        bin.install "runtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.0/runtui_darwin_arm64.tar.gz"
      sha256 "260395a595506d882cdae8b0017764034612b31bd1ca5a0be52095b6e1019c69"

      define_method(:install) do
        bin.install "runtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.0/runtui_linux_amd64.tar.gz"
      sha256 "c12f66385fc7bd8987fec75b9c7ce0baa8ea12192c2d96fec97dc776677677cd"
      define_method(:install) do
        bin.install "runtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.0/runtui_linux_arm64.tar.gz"
      sha256 "5c484dd7e41aba1b460fc099667c25ce992b05d1995f3fe3a43b12f471a337dd"
      define_method(:install) do
        bin.install "runtui"
      end
    end
  end

  test do
    system "#{bin}/runtui --version"
  end
end
