# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runtui < Formula
  desc "Interactive TUI for running project tasks"
  homepage "https://github.com/pedromendonka/runtui"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.2/runtui_darwin_amd64.tar.gz"
      sha256 "3be1354e2ea1e02ebcdb41cb2fe1e52db0e0aa47e5f1070fef803c02d2c73e7a"

      define_method(:install) do
        bin.install "runtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.2/runtui_darwin_arm64.tar.gz"
      sha256 "daad35e274baea78ba5c231239fc757149ae1d5de8cf899f18ebba428021d34d"

      define_method(:install) do
        bin.install "runtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.2/runtui_linux_amd64.tar.gz"
      sha256 "21272a25b0145ebf4b3ce8f42e8585ee20c569afa9611d3a9591d5049eaed945"
      define_method(:install) do
        bin.install "runtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedromendonka/runtui/releases/download/v0.1.2/runtui_linux_arm64.tar.gz"
      sha256 "f30b95c33dc2afbe4a60b357235c84802782b5d63c5b19280907a0568b7696ba"
      define_method(:install) do
        bin.install "runtui"
      end
    end
  end

  test do
    system "#{bin}/runtui --version"
  end
end
